language: generic
sudo: required

service:
  - docker

before_install:
  - docker build -t scottwoods/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true scottwoods/docker-react npm run test -- --coverage